/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as HouseRouteImport } from './routes/house'
import { Route as PlayRouteImport } from './routes/play'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as ApiKeeperStatusRouteImport } from './routes/api/keeper/status'
import { Route as ApiKeeperSubmitScoreRouteImport } from './routes/api/keeper/submit-score'
import { Route as ApiKeeperTickRouteImport } from './routes/api/keeper/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeeperStatusRoute = ApiKeeperStatusRouteImport.update({
  id: '/api/keeper/status',
  path: '/api/keeper/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeeperSubmitScoreRoute = ApiKeeperSubmitScoreRouteImport.update({
  id: '/api/keeper/submit-score',
  path: '/api/keeper/submit-score',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeeperTickRoute = ApiKeeperTickRouteImport.update({
  id: '/api/keeper/tick',
  path: '/api/keeper/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/docs': typeof DocsRoute
  '/house': typeof HouseRoute
  '/play': typeof PlayRoute
  '/treasury': typeof TreasuryRoute
  '/api/keeper/status': typeof ApiKeeperStatusRoute
  '/api/keeper/submit-score': typeof ApiKeeperSubmitScoreRoute
  '/api/keeper/tick': typeof ApiKeeperTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/docs': typeof DocsRoute
  '/house': typeof HouseRoute
  '/play': typeof PlayRoute
  '/treasury': typeof TreasuryRoute
  '/api/keeper/status': typeof ApiKeeperStatusRoute
  '/api/keeper/submit-score': typeof ApiKeeperSubmitScoreRoute
  '/api/keeper/tick': typeof ApiKeeperTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arena': typeof ArenaRoute
  '/docs': typeof DocsRoute
  '/house': typeof HouseRoute
  '/play': typeof PlayRoute
  '/treasury': typeof TreasuryRoute
  '/api/keeper/status': typeof ApiKeeperStatusRoute
  '/api/keeper/submit-score': typeof ApiKeeperSubmitScoreRoute
  '/api/keeper/tick': typeof ApiKeeperTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arena'
    | '/docs'
    | '/house'
    | '/play'
    | '/treasury'
    | '/api/keeper/status'
    | '/api/keeper/submit-score'
    | '/api/keeper/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/docs'
    | '/house'
    | '/play'
    | '/treasury'
    | '/api/keeper/status'
    | '/api/keeper/submit-score'
    | '/api/keeper/tick'
  id:
    | '__root__'
    | '/'
    | '/arena'
    | '/docs'
    | '/house'
    | '/play'
    | '/treasury'
    | '/api/keeper/status'
    | '/api/keeper/submit-score'
    | '/api/keeper/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArenaRoute: typeof ArenaRoute
  DocsRoute: typeof DocsRoute
  HouseRoute: typeof HouseRoute
  PlayRoute: typeof PlayRoute
  TreasuryRoute: typeof TreasuryRoute
  ApiKeeperStatusRoute: typeof ApiKeeperStatusRoute
  ApiKeeperSubmitScoreRoute: typeof ApiKeeperSubmitScoreRoute
  ApiKeeperTickRoute: typeof ApiKeeperTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keeper/status': {
      id: '/api/keeper/status'
      path: '/api/keeper/status'
      fullPath: '/api/keeper/status'
      preLoaderRoute: typeof ApiKeeperStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keeper/submit-score': {
      id: '/api/keeper/submit-score'
      path: '/api/keeper/submit-score'
      fullPath: '/api/keeper/submit-score'
      preLoaderRoute: typeof ApiKeeperSubmitScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keeper/tick': {
      id: '/api/keeper/tick'
      path: '/api/keeper/tick'
      fullPath: '/api/keeper/tick'
      preLoaderRoute: typeof ApiKeeperTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArenaRoute: ArenaRoute,
  DocsRoute: DocsRoute,
  HouseRoute: HouseRoute,
  PlayRoute: PlayRoute,
  TreasuryRoute: TreasuryRoute,
  ApiKeeperStatusRoute: ApiKeeperStatusRoute,
  ApiKeeperSubmitScoreRoute: ApiKeeperSubmitScoreRoute,
  ApiKeeperTickRoute: ApiKeeperTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
